"""Initial migration

Revision ID: 0286ed2840c6
Revises: 
Create Date: 2025-03-24 22:45:24.064592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0286ed2840c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('id_empresa', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documentos', 'companies', ['id_empresa'], ['id'])
    op.add_column('rendicion', sa.Column('id_empresa', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rendicion', 'companies', ['id_empresa'], ['id'])
    op.add_column('solicitud', sa.Column('id_empresa', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'companies', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'id_empresa')
    op.drop_constraint(None, 'rendicion', type_='foreignkey')
    op.drop_column('rendicion', 'id_empresa')
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_column('documentos', 'id_empresa')
    # ### end Alembic commands ###
