"""Agregando nuevos campos a la tabla Documento

Revision ID: 06b116e370fa
Revises: 8cd1c197762f
Create Date: 2024-09-30 12:07:12.507377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b116e370fa'
down_revision: Union[str, None] = '8cd1c197762f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('tipo_viaje', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'tipo_viaje')
    # ### end Alembic commands ###
