"""fix ambiguous relationships in Rendicion and Solicitud

Revision ID: 0d6d25693e41
Revises: 
Create Date: 2025-04-27 11:39:20.464689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6d25693e41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rendicion', sa.Column('id_aprobador', sa.Integer(), nullable=True))
    op.add_column('rendicion', sa.Column('nom_aprobador', sa.String(), nullable=True))
    op.add_column('rendicion', sa.Column('id_contador', sa.Integer(), nullable=True))
    op.add_column('rendicion', sa.Column('nom_contador', sa.String(), nullable=True))
    op.create_foreign_key(None, 'rendicion', 'users', ['id_aprobador'], ['id'])
    op.create_foreign_key(None, 'rendicion', 'users', ['id_contador'], ['id'])
    op.add_column('solicitud', sa.Column('id_aprobador', sa.Integer(), nullable=True))
    op.add_column('solicitud', sa.Column('nom_aprobador', sa.String(), nullable=True))
    op.add_column('solicitud', sa.Column('id_contador', sa.Integer(), nullable=True))
    op.add_column('solicitud', sa.Column('nom_contador', sa.String(), nullable=True))
    op.create_foreign_key(None, 'solicitud', 'users', ['id_aprobador'], ['id'])
    op.create_foreign_key(None, 'solicitud', 'users', ['id_contador'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_constraint(None, 'solicitud', type_='foreignkey')
    op.drop_column('solicitud', 'nom_contador')
    op.drop_column('solicitud', 'id_contador')
    op.drop_column('solicitud', 'nom_aprobador')
    op.drop_column('solicitud', 'id_aprobador')
    op.drop_constraint(None, 'rendicion', type_='foreignkey')
    op.drop_constraint(None, 'rendicion', type_='foreignkey')
    op.drop_column('rendicion', 'nom_contador')
    op.drop_column('rendicion', 'id_contador')
    op.drop_column('rendicion', 'nom_aprobador')
    op.drop_column('rendicion', 'id_aprobador')
    # ### end Alembic commands ###
