"""Añadir campos id_user e id_numero_rendicion

Revision ID: 163334c30b7b
Revises: 9f9259968448
Create Date: 2024-11-29 16:15:16.306224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163334c30b7b'
down_revision: Union[str, None] = '9f9259968448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
