"""Inicializar migración

Revision ID: 34e7ead53972
Revises: 920563c7d140
Create Date: 2024-08-28 18:24:35.482337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e7ead53972'
down_revision: Union[str, None] = '920563c7d140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('destino', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'destino')
    # ### end Alembic commands ###
