"""Add zona_venta to User table

Revision ID: 3bd951eef488
Revises: 83ffbb169f29
Create Date: 2024-08-11 23:21:39.664197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bd951eef488'
down_revision: Union[str, None] = '83ffbb169f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zona_venta', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zona_venta')
    # ### end Alembic commands ###
