"""Inicializar migración

Revision ID: 4c59e10448b3
Revises: 24446c66c13e
Create Date: 2024-08-31 01:27:37.413233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c59e10448b3'
down_revision: Union[str, None] = '24446c66c13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('origen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'origen')
    # ### end Alembic commands ###
