"""Add cargo field to User model

Revision ID: 4e913a27f0ed
Revises: 
Create Date: 2024-08-11 01:21:37.050256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e913a27f0ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_empresas_id', table_name='empresas')
    op.drop_index('ix_empresas_name', table_name='empresas')
    op.drop_table('empresas')
    op.add_column('users', sa.Column('cargo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cargo')
    op.create_table('empresas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresas_pkey')
    )
    op.create_index('ix_empresas_name', 'empresas', ['name'], unique=True)
    op.create_index('ix_empresas_id', 'empresas', ['id'], unique=False)
    # ### end Alembic commands ###
