"""Agregar campos a la tabla User

Revision ID: 597e20802586
Revises: fe81906d04e8
Create Date: 2024-09-08 21:15:38.055416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597e20802586'
down_revision: Union[str, None] = 'fe81906d04e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('fecha_rendicion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'fecha_rendicion')
    # ### end Alembic commands ###
