"""Añadir campos id_user e id_numero_rendicion

Revision ID: 6238e9780f81
Revises: 163334c30b7b
Create Date: 2024-11-29 17:27:25.555667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6238e9780f81'
down_revision: Union[str, None] = '163334c30b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
