"""Add jefe_id column to User table

Revision ID: 73730a5c9ee7
Revises: e895385e8a2b
Create Date: 2024-08-13 23:45:59.963748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73730a5c9ee7'
down_revision: Union[str, None] = 'e895385e8a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jefe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['jefe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'jefe_id')
    # ### end Alembic commands ###
