"""Agregar campos a la tabla User

Revision ID: 7481aae07406
Revises: 597e20802586
Create Date: 2024-09-08 23:57:42.544701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7481aae07406'
down_revision: Union[str, None] = '597e20802586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('numero_rendicion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'numero_rendicion')
    # ### end Alembic commands ###
