"""Add id_empresa and estado to users

Revision ID: 7fa078be429b
Revises: 6238e9780f81
Create Date: 2024-12-09 13:25:23.132409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa078be429b'
down_revision: Union[str, None] = '6238e9780f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_empresa', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('estado', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['id_empresa'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'estado')
    op.drop_column('users', 'id_empresa')
    # ### end Alembic commands ###
