"""Add dni field to User model

Revision ID: 83ffbb169f29
Revises: 4e913a27f0ed
Create Date: 2024-08-11 01:30:28.737910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ffbb169f29'
down_revision: Union[str, None] = '4e913a27f0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dni', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dni')
    # ### end Alembic commands ###
