"""Agrega campos fecha_registro y fecha_actualizacion a la tabla rendicion

Revision ID: 86e78ac56664
Revises: ab5674cf8a16
Create Date: 2024-11-19 00:23:41.728363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e78ac56664'
down_revision: Union[str, None] = 'ab5674cf8a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rendicion', sa.Column('fecha_registro', sa.Date(), nullable=True))
    op.add_column('rendicion', sa.Column('fecha_actualizacion', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rendicion', 'fecha_actualizacion')
    op.drop_column('rendicion', 'fecha_registro')
    # ### end Alembic commands ###
