"""Agregar campos a la tabla User

Revision ID: 8cd1c197762f
Revises: 7481aae07406
Create Date: 2024-09-11 15:13:45.951221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd1c197762f'
down_revision: Union[str, None] = '7481aae07406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cuenta_bancaria', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banco', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banco')
    op.drop_column('users', 'cuenta_bancaria')
    # ### end Alembic commands ###
