"""Agregar columna id_user a la tabla users

Revision ID: 8e3b6a4be32e
Revises: 
Create Date: 2025-03-04 22:59:42.791362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3b6a4be32e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_id_user', table_name='users')
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.create_index('ix_users_id_user', 'users', ['id_user'], unique=True)
    # ### end Alembic commands ###
