"""Inicializar migración

Revision ID: 920563c7d140
Revises: 
Create Date: 2024-08-28 18:16:58.886315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920563c7d140'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('responsable', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('area', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('ceco', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('tipo_anticipo', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('fecha_viaje', sa.Date(), nullable=True))
    op.add_column('documentos', sa.Column('dias', sa.Integer(), nullable=True))
    op.add_column('documentos', sa.Column('presupuesto', sa.Float(), nullable=True))
    op.add_column('documentos', sa.Column('banco', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('numero_cuenta', sa.String(), nullable=True))
    op.drop_column('documentos', 'destino')
    op.drop_column('documentos', 'gasto_deducible')
    op.drop_column('documentos', 'origen')
    op.drop_column('documentos', 'tipo_servicio')
    op.drop_column('documentos', 'gasto_nodeducible')
    op.drop_column('documentos', 'tipo_formulario')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('tipo_formulario', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('gasto_nodeducible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('tipo_servicio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('origen', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('gasto_deducible', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('destino', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('documentos', 'numero_cuenta')
    op.drop_column('documentos', 'banco')
    op.drop_column('documentos', 'presupuesto')
    op.drop_column('documentos', 'dias')
    op.drop_column('documentos', 'fecha_viaje')
    op.drop_column('documentos', 'tipo_anticipo')
    op.drop_column('documentos', 'ceco')
    op.drop_column('documentos', 'area')
    op.drop_column('documentos', 'responsable')
    # ### end Alembic commands ###
