"""Añadir campos id_user e id_numero_rendicion

Revision ID: 9f9259968448
Revises: a711ceb6a8b5
Create Date: 2024-11-29 16:14:29.685185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9259968448'
down_revision: Union[str, None] = 'a711ceb6a8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('id_user', sa.Integer(), nullable=True))
    op.add_column('documentos', sa.Column('id_numero_rendicion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'id_numero_rendicion')
    op.drop_column('documentos', 'id_user')
    # ### end Alembic commands ###
