"""initial migration

Revision ID: a55839521701
Revises: 875cc6eb7511
Create Date: 2024-10-14 18:48:51.601886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55839521701'
down_revision: Union[str, None] = '875cc6eb7511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['idUser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendicion_id'), 'rendicion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendicion_id'), table_name='rendicion')
    op.drop_table('rendicion')
    # ### end Alembic commands ###
