"""Add fecha_creacion, fecha_actualizacion, and estado to RendicionSolicitud

Revision ID: a711ceb6a8b5
Revises: a945e83bf097
Create Date: 2024-11-26 09:20:35.483382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a711ceb6a8b5'
down_revision: Union[str, None] = 'a945e83bf097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
