"""Add fecha_creacion, fecha_actualizacion, and estado to RendicionSolicitud

Revision ID: a945e83bf097
Revises: 86e78ac56664
Create Date: 2024-11-26 09:18:01.927725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a945e83bf097'
down_revision: Union[str, None] = '86e78ac56664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idUser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_id'), 'solicitud', ['id'], unique=False)
    op.create_table('rendicion_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rendicion_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rendicion_id'], ['rendicion.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendicion_solicitud_id'), 'rendicion_solicitud', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendicion_solicitud_id'), table_name='rendicion_solicitud')
    op.drop_table('rendicion_solicitud')
    op.drop_index(op.f('ix_solicitud_id'), table_name='solicitud')
    op.drop_table('solicitud')
    # ### end Alembic commands ###
