"""Agregar columna id_user a la tabla users

Revision ID: bd5fd5647519
Revises: 
Create Date: 2025-03-04 00:47:00.627591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5fd5647519'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_column('users', 'id_user')
    # ### end Alembic commands ###
