"""Add new fields to Documentos table

Revision ID: e895385e8a2b
Revises: 3bd951eef488
Create Date: 2024-08-11 23:44:11.164337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e895385e8a2b'
down_revision: Union[str, None] = '3bd951eef488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('tipo_cambio', sa.Float(), nullable=True))
    op.add_column('documentos', sa.Column('afecto', sa.Float(), nullable=True))
    op.add_column('documentos', sa.Column('inafecto', sa.Float(), nullable=True))
    op.add_column('documentos', sa.Column('rubro', sa.String(), nullable=True))
    op.add_column('documentos', sa.Column('cuenta_contable', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'cuenta_contable')
    op.drop_column('documentos', 'rubro')
    op.drop_column('documentos', 'inafecto')
    op.drop_column('documentos', 'afecto')
    op.drop_column('documentos', 'tipo_cambio')
    # ### end Alembic commands ###
